### ISSUE TITLE
unable to retrieve ubxllib using west: FATAL ERROR: can't import from project ubxlib

### ISSUE THREAD

**Issue by mabroens** [u-blox/ubxlib#173]
Hi,

I am trying to add ubxlib to my west repo following the steps here [https://github.com/u-blox/ubxlib/tree/master/port/platform/zephyr](url) :
```
  remotes:
    - name: u-blox
      url-base: git@github.com:u-blox

  projects:
    - name: ubxlib
      remote: u-blox
      path: ubxlib
      revision: v1.2.0
      import: true
      clone-depth: 1
```
but whenever i run `west update` i get an error:
```
FATAL ERROR: can't import from project ubxlib
  Expected to import from west.yml at revision 86c97d39dd43c2c5f1ce08a5a4d1619927b8f832
  Hint: possible manifest file fixes for ubxlib:
          - set "revision:" to a git ref with this file at URL https://github.com/u-blox/ubxlib
          - remove the "import:"
        Use "west -vvv update" to debug.
```

BTW i had to chage the url to:
```
    - name: u-blox
      url-base: https://github.com/u-blox    
```
for it to work

does anyone have any suggestions?

Br Martijn
