### ISSUE TITLE
Zephyr dependancy on nRF Connect

### ISSUE THREAD

**Issue by mtfurlan** [u-blox/ubxlib#99]
As far as I can tell, the only reason ubxlib under zephyr depends on  nRF Connect is to get [unity](https://github.com/ThrowTheSwitch/unity) (and this only matters if you want to build `port/platform/zephyr/runner`, if you just use ubxlib it works fine).

We can make west fetch unity by adding a `west.yml`
```yaml
manifest:
  remotes:
    - name: ThrowTheSwitch
      url-base: https://github.com/ThrowTheSwitch
  projects:
    - name: Unity
      remote: ThrowTheSwitch
      revision: v2.5.2
      path: test/cmock/vendor/unity
```

Though for some reason you have unity in `$zephyr_workspace/test`, which is kinda weird, everything else is in `$zephyr_workspace/modules`.
I found an example of someone else using unity with zephyr, and they [put it in `$zephyr_workspace/modules`](https://github.com/swedishembedded/testing/blob/main/west.yml#L16).

As far as I can tell, the west.yml *must* be in the repo root, unfortunately and we can't put it in port/platform/zephyr

I think it would be good to simplify the install instructions by
* use ubxlib as a normal zephyr module from your project's west.yml
* removing the stuff about ZEPHYR_EXTRA_MODULES
* not requiring nRF Connect

So if this is fine, I can make a PR to add the west.yml and change the documentation.
